server:
  port: 8081
spring:
  application:
    name: UserServiceApp

  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: root
    password: zoozoo

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/